### Endpoints

### 1) Signup
POST http://localhost:3003/users/signup
Content-type: APPLICATION/JSON
{
    "name": "teste",
    "email": "teste@gmail.com",
    "password": "123456"
}


### 2) Login
POST http://localhost:3003/users/login
Content-type: APPLICATION/JSON
{
    "email": "teste@gmail.com",
    "password": "123456"
}