### Endpoints

### 1) Signup
POST http://localhost:3003/users/signup
Content-type: APPLICATION/JSON
{
    "name": "Teste",
    "email": "testando@gmail.com",
    "password": "123456"
}


### 2) Login
POST http://localhost:3003/users/login
Content-type: APPLICATION/JSON
{
    "email": "teste@gmail.com",
    "password": "123456"
}

### 3) Pegar próprio perfil (Get Own Profile)
GET http://localhost:3003/users/profile
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImEzMDgxMGQyLTkyNGQtNDEyMS05MzU4LWM0ZTY2NjViMTZlNCIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjQxNTQ0OTQsImV4cCI6MTY2NDI0MDg5NH0.lKVZwM74amcek0TpfkaEgCKVHcLJx8aNsD9N1Xt7gcM

### 4) Pegar perfil de outro usuário
GET http://localhost:3003/users/:id
Path Params -> id: a30810d2-924d-4121-9358-c4e6665b16e4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImEzMDgxMGQyLTkyNGQtNDEyMS05MzU4LWM0ZTY2NjViMTZlNCIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjQxNTQ0OTQsImV4cCI6MTY2NDI0MDg5NH0.lKVZwM74amcek0TpfkaEgCKVHcLJx8aNsD9N1Xt7gcM

### 5) Criar receita
POST http://localhost:3003/recipe
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImEzMDgxMGQyLTkyNGQtNDEyMS05MzU4LWM0ZTY2NjViMTZlNCIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjQxNTQ0OTQsImV4cCI6MTY2NDI0MDg5NH0.lKVZwM74amcek0TpfkaEgCKVHcLJx8aNsD9N1Xt7gcM

### 6) Pegar receita
GET http://localhost:3003/recipe/:id
Authorization: 